server:
  port: 10010
spring:
  application:
    name: gateway
  cloud:
    nacos:
#      server-addr: http://172.16.0.2:8848
#      server-addr: nacos:8848
      server-addr: nginx_nacos:80
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true #解决options请求被拦截的问题
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods:
              - GET
              - POST
              - OPTIONS
            allowCredentials: true
            maxAge: 3600

      default-filters: # 默认网关
      #        - AddRequestHeader=hmz,this is super awkward
      routes: # 网关路由配置
        - id: user-service # 路由id
          uri: lb://user-service # 路由目标地址 load balance
          predicates: # 路由断言
            - Path=/user/** # 这个是按照路径匹配，/user/ 开头就符合
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**
#          filters:
#            - AddRequestHeader=hmz,this is super awkward
