server:
  port: 8081
spring:
  datasource:
#    url: jdbc:mysql://10.22.191.35:1234/cloud_user?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
    url: jdbc:mysql://mysql:3306/cloud_user?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: hmz990203
    driver-class-name: com.mysql.cj.jdbc.Driver
#  shardingsphere:
#    sharding:
#      default-database-strategy:
#      tables:

mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true

