server:
  port: 8088
spring:
  datasource:
    #    url: jdbc:mysql://10.22.191.35:1234/cloud_order?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    url: jdbc:mysql://mysql:3306/cloud_order?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: hmz990203
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    # todo 搭建集群时 orderservice 就报错 failed to req API:/nacos/v1/ns/instance after all servers 加了一个_就好了 但是不知道为什么
    name: order-service

  cloud:
    nacos:
#      单机
#      server-addr: nacos:8848
#      容器中通过nginx代理后，直接从外网访问也能行得通
#      server-addr: http://10.51.190.80:80
#      容器中的内网地址
      server-addr: nginx_nacos:80
      discovery:
        # 解决ipv4("nacos") not found
        ip-type: IPv4
#        cluster-name: HZ
#        namespace: 355aa1cb-48d2-409e-8d58-f7aed2fd1049 # dev环境
#        ephemeral: false # 是否是临时实例

#mybatis:
#  type-aliases-package: cn.itcast.user.pojo
#  configuration:
#    map-underscore-to-camel-case: true

userservice:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule  # 负载均衡规则
ribbon:
  eager-load:
    enabled: true # 开启饥饿加载
    clients: # 指定饥饿加载的服务名称
      - user-service
#      - xxxservice

#feign:
#  httpclient:
#    enabled: true # 支持HttpClient的开关
#    max-connections: 200 # 最大连接数
#    max-connections-per-route: 50 # 单个路径的最大连接数